import { CSSProperties } from 'react';
import theme from './constants/colors';

const styles = (): { [key: string]: CSSProperties } => ({
  main: {
    minHeight: '100vh',
    backgroundColor: '#f4f4f4',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    color: '#000000',
    fontFamily: 'Open Sans',
  },
  navbar: {
    backgroundColor: theme.primaryColor,
    position: 'sticky',
  },
  title: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#000000',
    alignSelf: 'center',
  },
  topBar: {
    display: 'flex',
    flexDirection: 'row',
    color: '#000000',
    justifyContent: 'space-between',
    padding: 10,
  },
  topBarContainer: {
    display: 'flex',
    flexDirection: 'row',
    color: '#000000',
    alignItems: 'center',
  },
  topBarContainerTitle: {
    display: 'flex',
    flexDirection: 'column',
    color: '#000000',
    fontSize: 14,
  },
  topBarTitle: {
    fontSize: 32,
    fontWeight: 600,
  },
  aboutUs: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    background: '#ffffff',
    color: '#000000',
    padding: 10,
  },
  aboutUsHeading: {
    display: 'flex',
    justifyContent: 'center',
    background: '#ffffff',
    color: theme.secondaryColor,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 700,
  },
  aboutUsSubHeading: {
    display: 'flex',
    justifyContent: 'center',
    background: '#ffffff',
    color: theme.primaryColor,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 700,
  },
  aboutUsText: {
    display: 'flex',
    justifySelf: 'center',
    background: '#ffffff',
    color: '#000000',
    textAlign: 'center',
    fontSize: 16,
    width: '40%',
    margin: 'auto',
  },
  services: {
    display: 'flex',
    flexDirection: 'column',
    padding: 10,
  },
  servicesHeader: {
    display: 'flex',
    justifyContent: 'center',
    background: '#ffffff',
    color: '#000000',
    textAlign: 'center',
  },
  servicesSubHeading: {
    display: 'flex',
    justifyContent: 'center',
    background: '#ffffff',
    color: theme.primaryColor,
    textAlign: 'center',
    fontSize: 28,
    fontWeight: 700,
  },
  doctorsContainer: {
    display: 'flex',
    justifyContent: 'center',
    background: '#ffffff',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    color: '#000000',
  },
  contactUs: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    background: '#1f2b6c',
    color: '#ffffff',
    padding: 20,
    gap: 10,
  },
  doctorName: {
    display: 'flex',
    justifyContent: 'center',
    fontSize: 18,
    fontWeight: 600,
    color: theme.primaryColor,
    marginBottom: 12,
  },
  doctorType: {
    display: 'flex',
    justifyContent: 'center',
    fontSize: 18,
    fontWeight: 700,
    color: theme.primaryColor,
  },
  viewProfileButton: {
    display: 'flex',
    color: theme.tertiaryColor,
  }
});

export default styles;
